added signup page
gdsc-meru-uni/votting-app pull request #1
Opened 2023-11-16 15:06 UTC by Paulmuia

created signup page

2023-11-16 20:02 UTC, Piexie3 requested changes
create a stateless widget for this class if you will not need to rebuilt the widget or using setState() anywhere

2023-11-16 20:02 UTC, Piexie3 commented on lib/pages/signup page.dart
> +                                      borderSide: const BorderSide(
Create a Util class for all the text fields

2023-11-16 20:02 UTC, Piexie3 commented on lib/pages/signup page.dart
> +                                      borderRadius: BorderRadius.circular(15),
create one Util class for text field to minimise repetition

2023-11-17 14:55 UTC, Paulmuia commented on lib/pages/signup page.dart
> +                                      borderRadius: BorderRadius.circular(15),
created a util class for all textfields and imlimented it in the signup page

2023-11-17 14:56 UTC, Paulmuia commented
created a util class for all textfields and imlimented it in the signup page

2023-11-19 03:52 UTC, Piexie3 requested changes

2023-11-19 03:52 UTC, Piexie3 commented on lib/pages/signup page.dart
> +  Widget build(BuildContext context) {
```suggestion
  Widget build(BuildContext context) {
  // initialize your controllers here
 final TextEditingController firstNameController = TextEditingController();
final TextEditingController lastNameController = TextEditingController();
final TextEditingController idController = TextEditingController();
```

2023-11-19 03:52 UTC, Piexie3 commented on lib/pages/signup page.dart
> +                            controller: TextEditingController(),
```suggestion
                            controller:  firstNameController ,
```

2023-11-19 03:52 UTC, Piexie3 commented on lib/pages/signup page.dart
> +                            controller: TextEditingController(),
make sure to change all the controllers

```suggestion
                            controller: lastNameController,
```

2023-11-22 12:26 UTC, Paulmuia commented
modified controllers

2023-11-22 12:32 UTC, Paulmuia commented
added login page

2023-11-23 02:45 UTC, Piexie3 approved these changes

2023-11-23 02:46 UTC, merged